Feature/first sight
vircadia/vircadia-web pull request #12
Opened 2021-06-09 14:24 UTC by digisomni

This PR is based on PR #10.

2021-07-16 06:38 UTC, digisomni commented
This should be merged into master before continuing work on TypeScript support, that way everything can be migrated all at once.

2021-07-16 07:41 UTC, ctrlaltdavid requested changes

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/components/MainScene.vue
> +            }, {});
Shouldn't really use strings for property IDs in script. This and similar could be written...
```suggestion
            this.$store.state.Entities.addEntity(this.scene, {
                name: 'box',
                type: 'Shape',
                shape: 'box',
                position: { x: -5, y: 0, z: 0 },
                rotation: { x: -0.2, y: -0.4, z: 0 },
                dimensions: { x: 3, y: 3, z: 3 },
                color: { r: 1, g: 0, b: 0 }
            }, {});
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/entities/entities.js
> +    async addEntity (scene, properties, entityHostType) {
```suggestion
    async addEntity(scene, properties, entityHostType) {
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/entities/entities.js
> +    async deleteEntityByName (scene, name) {
```suggestion
    async deleteEntityByName(scene, name) {
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/entities/entities.js
> +    async deleteEntityById (scene, id) {
```suggestion
    async deleteEntityById(scene, id) {
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/debugging/debug.js
> +    function error (type, string) {
```suggestion
    function error(type, string) {
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/metaverse/metaverse.js
> +    getError (error, stringify) {
```suggestion
    getError(error, stringify) {
```

2021-07-16 07:41 UTC, ctrlaltdavid commented on src/modules/metaverse/metaverse.js
> +        if (stringify === true) {
```suggestion
        if (stringify) {
```

2021-07-16 19:33 UTC, ctrlaltdavid requested changes

2021-07-16 19:33 UTC, ctrlaltdavid commented on src/components/MainScene.vue
> +            }, {});
Similar changes to be made here and below.

2021-07-19 08:42 UTC, ctrlaltdavid approved these changes

2021-07-19 08:44 UTC, merged