Continuation of refactor to TypeScript
vircadia/vircadia-web pull request #20
Opened 2021-08-12 23:33 UTC by Misterblue

This is building on "feature/refactor-to-typescript" branch to merge all of the code from 'master' into a TypeScript based version and doing some merging of build/checking code from vircadia-web-sdk.

The steps are planned to be:

- [x] add ESLint rules from -web-sdk and fix up code
- [ ] add style and menu setup from -web master
- [ ] add Vuex modules for state
- [ ] port .vue files from master

2021-09-07 07:19 UTC, digisomni requested changes

2021-09-08 16:55 UTC, Misterblue commented on src/global.d.ts
> +type AnyValue = KeyedCollection | string | number | unknown;
I don't see the change here. Is it the blank line after?

2021-09-08 17:13 UTC, Misterblue commented on src/components/overlays/OverlayManager.vue
> +function defineComponent(
Embarrassment at not deleting old code.

2021-09-08 17:44 UTC, Misterblue commented
I incorporated the suggested changes into a commit that I added to this PR. (Retrospectively, I notice I could have combined your changes into a batch commit. I'll figure out how to effectively use Github someday).

2021-09-08 20:33 UTC, digisomni commented on src/global.d.ts
> +type AnyValue = KeyedCollection | string | number | unknown;
Yup, just a new line at the end of file.

2021-09-09 14:47 UTC, merged